FROM loicfrering/elixir
MAINTAINER Loïc Frering <loic.frering@gmail.com>

# Install Phoenix
RUN mix archive.install --force https://github.com/phoenixframework/phoenix/releases/download/v0.11.0/phoenix_new-0.11.0.ez

# Working directory
WORKDIR /work

# Default command
CMD ["bash"]
